export interface User {
  username: string,
  password?: string,
  email?: string,
  role?: String,
  gamer?: string,
  team?: string,
  sponsor?: string,
  country: string,
  photoUrl?: string,
  gameList?: string,
  linkList?: string,
  biography?: string,
  name: string,
  bornDate?: string,
}
